### PR TITLE
Use flag instead of stdin to supply file to process

### PR DESCRIPTION
**Pull request by JPrevost**
#### What does this PR do?

Changes from stdin to a supplied file path for signifying the MARC file to process.

#### Helpful background context

Debugging with stdin was proving difficult at best so switching this this now rather than later will make my life somewhat easier.

#### How can a reviewer manually see the effects of these changes?

- go run main.go parse -h
- go run main.go parse --rules fixtures/marc_rules.json fixtures/test.mrc
- go run main.go parse fixtures/test.mrc
- go run main.go parse - < fixtures/record1.mrc

#### Requires Full Reindexing of all Sources?
NO

#### Includes new or updated dependencies?
NO

### CODE REVIEW

**Comment by gravesm** [comment]
I think I'd like to still be able to read from stdin. I'd also suggest that the input file be an argument rather than an option. Having a default rules file makes sense, but having a default marc file doesn't. So the marc file would be required.

**Comment by JPrevost** [comment]
Ah... I didn't fully understand the defaults thing there. I agree and can fix that bit.

Can you describe the use case in which maintaining to options for file input is beneficial so I understand why you are suggesting we need both? I can look into adding that to the PR if we agree the added complexity is worthwhile.

**Comment by JPrevost** [comment]
@gravesm I've addressed your comments. The `stdin` stuff works as it did before but still hangs if neither a file is passed as an arg or via stdin. This is how it worked before as it's waiting for input obviously but just wanted to point out we don't do anything special to handle that case.

**Comment by JPrevost** [comment]
Also, this should probably check for the presence of the file arg rather than waiting for it to error.

**Comment by JPrevost** [comment]
I've added another commit to explicitly check for the file flag being set and if it was not falling back to stdin rather than just looking for an error opening a non-existent file as the trigger to use stdin.

**Pull request merged**
